project:
  type: book
  output-dir: docs

book:
  title: "Data Analysis Toolkit for Food and Nutrition Sciences"
  repo-url: https://github.com/ggkuhnle/data-analysis-projects
  repo-actions: [edit, issue]
  page-navigation: true
  chapters:
    - index.qmd
    - syllabus.qmd

    - part: "01 Infrastructure"
      chapters:
        - notebooks/01_infrastructure/index.qmd
        - notebooks/01_infrastructure/0_getting_started.ipynb
        - notebooks/01_infrastructure/1.1_what_is_data_science_env.ipynb
        - notebooks/01_infrastructure/1.2_python_vs_r.ipynb
        - notebooks/01_infrastructure/1.3_intro_to_git.ipynb
        - notebooks/01_infrastructure/1.4_quarto_basics.ipynb

    - part: "02 Programming Basics"
      chapters:
        - notebooks/02_programming_basics/index.qmd
        - notebooks/02_programming_basics/2.0_intro_to_programming.ipynb
        - notebooks/02_programming_basics/2.1_programming_fundamentals.ipynb
        - notebooks/02_programming_basics/2.2_data_types_conversion.ipynb
        - notebooks/02_programming_basics/2.3_functions_loops.ipynb
        - notebooks/02_programming_basics/2.4_data_structures.ipynb
        - notebooks/02_programming_basics/2.5_input_output.ipynb
        - notebooks/02_programming_basics/2.6_oop_basics.ipynb

    - part: "03 Data Handling"
      chapters:
        - notebooks/03_data_handling/index.qmd
        - notebooks/03_data_handling/3.0_introduction_to_data_handling.ipynb
        - notebooks/03_data_handling/3.1_principles_of_tidy_data.ipynb
        - notebooks/03_data_handling/3.2_importing_data.ipynb
        - notebooks/03_data_handling/3.3_data_cleaning.ipynb
        - notebooks/03_data_handling/3.4_reshaping_merging.ipynb
        - notebooks/03_data_handling/3.5_feature_engineering_and_calculation.ipynb
        - notebooks/03_data_handling/3.6_data_aggregation.ipynb

    - part: "04 Data Analysis"
      chapters:
        - notebooks/04_data_analysis/index.qmd
        - notebooks/04_data_analysis/4.1_distributions_visualisation.ipynb
        - notebooks/04_data_analysis/4.2_exploratory_data_analysis.ipynb
        - notebooks/04_data_analysis/4.3_correlation_analysis.ipynb
        - notebooks/04_data_analysis/4.4_statistical_testing.ipynb
        - notebooks/04_data_analysis/4.5_regression_modelling.ipynb
        - notebooks/04_data_analysis/4.6_logistic_and_survival.ipynb
        - notebooks/04_data_analysis/4.7_clinical_trial_analysis.ipynb
        - notebooks/04_data_analysis/4.8_clinical_trial_analysis_bp.ipynb

    - part: "05 Advanced"
      chapters:
        - notebooks/05_advanced/index.qmd
        - notebooks/05_advanced/5.1_bayesian_methods.ipynb
        - notebooks/05_advanced/5.2_workflow_automation.ipynb
        - notebooks/05_advanced/5.3_advanced_bayesian.ipynb
        - notebooks/05_advanced/5.4_databases_sql.ipynb
        - notebooks/05_advanced/5.5_dashboards.ipynb

    - part: "06 Qualitative"
      chapters:
        - notebooks/06_qualitative/index.qmd
        - notebooks/06_qualitative/6.1_intro_qualitative_research.ipynb
        - notebooks/06_qualitative/6.2_text_analysis.ipynb

    - part: "10 Mini Projects"
      chapters:
        - notebooks/10_mini_projects/index.qmd
        - notebooks/10_mini_projects/10.1_clinical_trial.ipynb
        - notebooks/10_mini_projects/10.2_epidemiology_case_study.ipynb
        - notebooks/10_mini_projects/10.3_handling_missing_data.ipynb
        - notebooks/10_mini_projects/10.4_metabolomics.ipynb
        - notebooks/10_mini_projects/10.5_machine_learning.ipynb
        - notebooks/10_mini_projects/10.6_ai.ipynb
        - notebooks/10_mini_projects/10.7_llm.ipynb
        - notebooks/10_mini_projects/10.8_Bayesian_vs_Frequentist.ipynb
        - notebooks/10_mini_projects/10.9_fortran.ipynb

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
