name: Quarto Publish

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'  # Specify the R version you need

      - name: Install R and Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::jsonlite

      - name: Configure Git
        run: |
          git config --global g.g.kuhnle@reading.ac.uk "github-actions@github.com"
          git config --global ggkuhnle "GitHub Actions"

      - name: Clean up existing gh-pages worktree
        run: |
          git worktree remove gh-pages --force || true
          git branch -D gh-pages || true
          rm -rf gh-pages || true

      - name: Render and Publish
        run: |
          quarto render
          quarto publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

