name: Deploy Quarto Site to GitHub Pages
on:
  push:
    branches:
      - main
      - groks-revisions  # Trigger on pushes to main or groks-revisions
  pull_request:
    branches:
      - main
      - groks-revisions  # Trigger on PRs to these branches
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow writing to gh-pages branch
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for Quarto rendering

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Match notebook kernel (Python 3.9.7)

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install pandas, numpy, scikit-learn, matplotlib, jupyter, lifelines

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.57'  # Valid Quarto version for Linux

      - name: Render Quarto site
        run: |
          quarto render  # Render to _site/, no publish
        env:
          QUARTO_PYTHON: python3  # Ensure correct Python

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/groks-revisions'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true  # Overwrite gh-pages history