name: Render Quarto Files
on:
  push:
    branches: 
      - main
      - groks-revisions
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.0/quarto-1.4.0-linux-amd64.deb
          sudo dpkg -i quarto-1.4.0-linux-amd64.deb
      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      - name: Render Quarto
        run: quarto render --to html --output-dir docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
